
package com.github.griffty.finalproject.ui;

import com.github.griffty.finalproject.ui.side.SideBar;
import com.github.griffty.finalproject.ui.side.panels.StartPanel;
import lombok.Getter;

import static com.almasb.fxgl.dsl.FXGL.*;

/**
 * Central UI manager responsible for creating and registering top-level UI elements.
 *
 * <p>This class implements a lazy singleton to provide a single point of access to
 * UI-related resources such as the application's {@link SideBar} and the
 * {@link CameraController} instance.</p>
 *
 * <p>It uses FXGL's utility methods (statically imported) to query application
 * dimensions and to add UI nodes to the game scene graph.</p>
 */
@Getter
public class UIManager {
    private static UIManager instance;

    /**
     * Obtain the singleton instance of {@link UIManager}, creating it on first use.
     *
     * @return the shared {@code UIManager} instance
     */
    public static UIManager get() {
        if (instance == null) {
            instance = new UIManager();
        }
        return instance;
    }

    /**
     * Recreate the singleton instance.
     *
     * <p>Useful for resetting UI state in tests or when restarting the game UI.
     * This will construct a new {@code UIManager} and replace the existing one.</p>
     */
    public static void reset() {
        instance = new UIManager();
    }

    /**
     * The application's main side bar UI component.
     *
     * <p>Accessors for this field are generated by Lombok's {@code @Getter}.</p>
     */
    private final SideBar sideBar;

    /**
     * Controller responsible for managing camera behavior and interactions.
     *
     * <p>Accessors for this field are generated by Lombok's {@code @Getter}.</p>
     */
    private final CameraController cameraController;

    /**
     * Construct a new UI manager, initializing the camera controller and the side bar.
     *
     * <p>The constructor creates the {@link CameraController} and then initializes
     * the side panel by calling {@link #initSidePanel()} which places the panel
     * on the right edge of the application window and shows the initial
     * {@link StartPanel}.</p>
     */
    public UIManager() {
        cameraController = new CameraController();
        sideBar = initSidePanel();
    }

    /**
     * Initialize and register the side panel UI.
     *
     * <p>This method constructs a {@link SideBar} with a fixed width (360) and a
     * height equal to the application height, positions it at the right edge of
     * the application window, adds it to the FXGL UI via {@code addUINode},
     * and shows the {@link StartPanel} as the initial content.</p>
     *
     * @return the constructed and registered {@link SideBar}
     */
    private SideBar initSidePanel() {
        double panelWidth = 360;
        double panelHeight = getAppHeight();

        SideBar sideBar = new SideBar(panelWidth, panelHeight);

        double x = getAppWidth() - panelWidth;
        double y = 0;

        addUINode(sideBar, x, y);
        sideBar.show(new StartPanel());
        return sideBar;
    }
}
